import React, { Component } from 'react';
import { Link } from 'react-router-dom';
import '../styles/Theory.css'
import ModernGreen from '../assets/pics/modern_floral_green.png';
import Moodboard from '../assets/Moodboard.png';
import NoraCatReveal from '../assets/NoraCatReveal.png';


export default class Rationale extends Component {
  render() {
    return (
      <div className='content' style={{backgroundImage: `url(${ModernGreen})`}}>
        <article className='foreground'>
            <section>
            <h1 className='main-heading'>Artwork Rationale</h1>
            <p className='paragraph'>
            I chose to do a Vtuber character as my internet art
            project because she is composed of animated artwork that exists only through my livestreams on the internet. 
            This is something we discussed when trying to define 'Internet Art'. Our class felt that it is artwork that 
            cannot exist without the internet. Vtubers originate from YouTube, the term itself means 'Viritual YouTuber'.
            Thus, vtuber artwork, the art of character design and animation, was born and only exists in online platforms that 
            require the internet. Vtubing and researching vtuber identity is currently my passion project across two of my university 
            courses so I felt Interactive Media would be a good place to showcase the practical side of the project. In my research 
            course, I have dived into vtuber gender performance and identity and it has strengthened my internet art's design process.
            </p>
            <h2 className='section-title'>Moodboard and Inspiration</h2>
            <img 
                className="wireframes-img"
                src={Moodboard}
                alt="A screenshot of the vtuber, Niwwu"
            />
            <p className='paragraph'>
            My inspiration for the artwork and subsequently the website came from various sources. The Vtuber Intro Card is what inpsired 
            my index/home page. I explain this further in my <Link to='/design' className='hyperlink'>Design section</Link>. I wanted 
            something a bit more unique than a red rose so that is what inspired the green colour. Green is quite an energising colour, 
            a quality that the vtuber character has to her. But I used darker greens to help 'calm' the areas of focus on the site as I 
            felt bright greens may be distracting when trying to read a paragraph like this. In the moodboard is a screenshot of Code Miko. 
            She is one of my biggest vtuber inspirations, though she is in 3D. For my digital prac next semester, I will be embarking on a 
            3D journey! 
            </p>
            <p className='paragraph'>
            In my previous website, I included some of the research I had done on the literature encasing vtuber identity and gender performance.
            Our Digital Humanities course has required us to synthesise that research and write an essay on it, which I would like to share here. 
            The essay uses a case study of a real-life male vtuber who performs as a female character instead of my own artwork. This is because I 
            wanted to share the disruptions in the discourse around gender performance and idenity that vtubers create. Overall my research 
            has informed my design decisions with regards to gender performance, I am a real-life female performing as a virtual female because 
            that is what I am most comfortable and familiar with at this point. But I want the community I create to feel welcomed in whatever gender 
            they align with because that is the essence of my artwork's purpose - to create a community that feels connected and safe, to support 
            expressions in identity and gender. I say this regards to my character's personality and social goals, whereas my interactive artwork 
            showcases how the community can form connections with and get to know my artwork (my character) through fun interactions. 
            </p>
            </section>

            <section>
            <h1 className='main-heading'>Vtuber Disruptions in Gender</h1>
            <p className='paragraph'>
            The purpose of this research paper is to investigate Nora Cat’s vtuber face reveal and how it presents and complicates the discourses surrounding gender identity and performance in online digital spaces. Nora Cat is a cute anime girl character played by a man who remains anonymous. This paper looks closely at how Nora Cat expresses their online female gender through the performance of their avatar as the real body behind the character is a male. Over the past few years, vtuber identity and gender expression is being critically analysed by Digital Humanities scholars as the research contributes to studies on the online digital human body. This paper draws theories, observations, and conclusions from numerous sources to offer a cohesive look at gender identity performance in Vtubing, to further our understanding of online virtual bodies. 
            </p>
            <p className='paragraph'>
            To unpack Nora Cat’s face reveal and gender performance I offer an analysis of what insights on vtubers and gender identity can be drawn from the event. Vtubers can partake in what is called “digital gender swapping” (Bredikhina & Giard 2022: 1643) where the performer is of a different gender to the avatar’s gender identity. In this case study, Nora Cat is a female character performed by a Japanese man. This can address some of the coded gender complications highlighted by Bredikhina and Giard as their research introduces us to the societal tensions Japanese men face under “hegemonic gender norms in Japan” (2022: 1644). I then focus on the effect Nora Cat’s online gender choice produces, some of which are highlighted by Bredikhina and Giard again. They present how gender swapping can still reproduce gender norms and stereotypes although there is a disruptiveness in the “practice of digital cross-dressing” (2022: 1643-1647). These arguments also tie into discourses and challenges around the prosumption of imagery and gender, and technology and gender (Turner 2022, William & Marquez 2015). Addressing these sections will be supplemented with the theories on gender identity found in the resources this paper uses.
            </p>
            <p className='paragraph'>
            In February 2018, Nora Cat was livestreaming on YouTube and through what seems like a glitch in the stream’s technology their real face was exposed to viewers for a few seconds. The reveal showed something viewers may not have been expecting – the face of a middle-aged Japanese male who was clearly the human behind the young and kawaī   anime girl character. Nora Cat is a virtual YouTuber who uses an anime girl avatar to represent themselves to the public online. Vtubers are defined as ‘virtual YouTubers’, content creators who use virtual 2D or 3D avatars as representations of themselves or a character they portray. Vtubers are not limited to YouTube, and many create content on other livestreaming platforms like Twitch. Nora Cat livestreams and posts videos on YouTube whose content ranges from gaming to lifestyle snippets. She is an underlining subject for gender analysis because of her virtual character design and her portrayal by a real-life Japanese man. The rise of vtubers over the past 7 years has brought about many different types of characters performed by various demographics of people. Interesting discussions over theories of online body representation, identity construction, and gender performance have begun to unfurl, particularly relating to how digital technology informs gender performance (Bredikhina & Giard 2022, Turner 2022). 
            </p>
            <p className='paragraph'>
            The field of Digital Humanities seeks to explore the intersection between technology and humanities, especially how technology impacts human culture, society, and the arts. Researching vtuber identity and gender expression is important as it sheds light on the evolving nature of online identities and how people use digital media to express their gender and sexuality. It also offers insights into the impact of virtual reality on human interactions, particularly the blurring of categories such as real and fictional, self, and other, and public and private. By examining the practices and processes of vtubers, researchers can better understand how technology is shaping human identity and expression in digital spaces. Studying vtuber's identities and gender expression can offer valuable insights to the field of Digital Humanities. Firstly, it can provide a deeper understanding of how online identities are constructed and performed in digital spaces. Vtubers use avatars to represent themselves, which allows for a level of anonymity and flexibility in their expression. This can help researchers analyse how digital technologies shape identity formation and representation.
            <br/>
            Secondly, studying vtubers can contribute to research on gender and gender expression in digital spaces. Many vtubers actively explore and challenge traditional gender roles and stereotypes in their content. This can help researchers better understand how new forms of media shape contemporary discussions around gender and identity. Overall, studying vtuber's identities and gender expression offers a unique and exciting lens through which to explore the intersections of technology, identity, and culture in the Digital Humanities.
            </p>
            <p className='paragraph'>
            I draw from theories and arguments posited by numerous authors. Deborah Lupton (2015) offers extensive research on digital sociology; the intertwining of digital technology, selfhood and embodiment which offer positions that I can analyse online virtual embodiment, selfhood, and gender in this case study. Liudmila Bredikhina (2020), Bredikhina and Agnès Giard (2022), and Natalie Yeo (2022) address some of the reasons why content creators turn to vtubing to represent themselves online and why someone like Nora Cat performs as a female character even though they are male in real life. 
            <br/>
            This research covers complex and sensitive issues like gender identity and expression. It sticks strictly to what the scholarship has to offer on online gender identity and does not offer, or is based off, any personal opinions on gender. No interviews or surveys were conducted, and the synthesised information comes from other scholar’s quantitative and qualitative data and further research. Usernames have also been changed to keep anonymity.
            </p>
            <p className='paragraph'>
            Insights on gender performance from Nora Cat’s face reveal
            </p>
            <p className='paragraph'>
            This first section begins to unpack the research topic by looking at the insights that can be gleaned from Nora Cat’s face reveal in the context of the Digital Humanities. Online gender identity and performance and digital selfhood and embodiment are two critical DH modals that are key to unpacking the event. I begin with further information on the event and how it was received by viewers. It is then imperative to note the category of vtubers Nora Cat falls into and its relation to gender identity as it directs the discussion towards digital, and virtual, selfhood and embodiment. 
            </p>
            <p className='paragraph'>
            At the time of the face reveal, Nora Cat had been livestreaming on YouTube since December 2017 and had garnered a following of around 57 000 YouTube subscribers. On February 4th, 2018, Twitter user pandaJacaranda posted a clip of Nora Cat’s technical glitch during a livestream which revealed her true identity – a middle-aged Japanese male (Loveridge 2018). The face reveal received mixed responses as some viewers felt shocked, while others separated the two identities, and some felt drawn and curious to engage with Nora Cat more (Baseel 2018). The event itself and the responses to Nora Cat’s actual identity spark unique outlooks on gender identity and representation through vtuber characters. Baseel noted that the viewers who separated Nora Cat’s female identity from the man who plays her did so because they felt it was no different to other female anime characters that are drawn and animated by men. However, viewers who were struck by the reveal felt that way because of how Nora Cat’s personality, mannerisms and expressions originate from a man embodying her. They could not separate the connections between content and creator. The community’s responses show the multi-faceted ways in which gender identity plays a role in the social structures and connections that form online between vtubers and their communities.
            </p>
            <img
                className="wireframes-img"
                src={NoraCatReveal}
                alt="Nora Cat's technical glitch revealing their real face."
                />
            <p className='paragraph'>
            Nora Cat’s face reveal introduces us to a community of male vtubers who incarnate themselves as virtual female characters. She is part of a large vtuber community known as babiniku. Babiniku is a Japanese term that means virtual female incarnation. It is an abbreviation of ‘bācharu bishōjo juniku,’ meaning virtual beautiful girl incarnation (Bredikhina & Giard 2022: 1116). These avatars typically take on an anime style appearance and are referred to as bishōjo, a beautiful and kawaī girl. Bredikhina and Giard state that “bishōjo avatars are used to socialize and create a community or a following on a social networking service (SNS) without showing a physical face” (2022: 1651). For men who may feel constricted in their real-life physical body, the accessibility of a different virtual body seems appealing. This was studied by Bredikhina (2020) who interviewed numerous English, French and Japanese vtubers. 16% of the English vtubers and 50% of the Japanese vtubers she surveyed were men using female rigs . Furthermore, 9% of En-vtubers and 24% of J-vtubers used their own male voice without modifications while 2% of En-vtubers and 20% of J-vtubers used voice modifications to sound female. 16% of En-vtubers and J-vtubers “trained” their voice to sound more feminine (Bredikhina 2020: 2-3). The percentages show that most babiniku vtubers are performing their female characters with female sounding voices, further embodying the conventional femininity of their avatars. ‘Embodying’ is a key term here as I begin to address this Japanese man’s virtual embodiment of Nora Cat. On a further note, Bredikhina’s results also show that a fair portion of these babiniku vtubers, especially in the context of Japanese culture, are using their natural male voices. Nora Cat does not fall into the sub-category of babiniku who use their natural male voices as she uses voice modifying software to make her sound more female. However, it feels important to address the implications that arise through male-voiced female characters. I argue that these results challenge the socially understood and coded markers of femininity and what is ‘means’ to be female. These male-voiced female characters represent femininity in an alternative code, one where a higher, lighter, and softer voice is not required to prove femininity and female gender identity. This contrasts Bredikhina and Giard’s research on the idealised representations of female avatars that are usually based on the “current standards to attractiveness” (2022: 1646), because the male’s voice does not fall into the category of standardised female attractiveness. It shows that these men are still assertive in their online and virtual female identities regardless of their explicitness of their real-life male identity.
            </p>
            <p className='paragraph'>
            Lupton draws from the works of Nippert-Eng and Haraway to describe digital embodiment as ‘territories of the self’ and the concept of the modern cyborg (2015: 39-40). Territories of the self refers to the extensions of the human body into spaces, other humans, and objects. Bredikhina and Giard apply this extension as a “rebirth” (2022: 1644) for people performing as virtual characters who can reconstruct their real-life human body into a new and different virtual body. We can view the virtual avatar as an object that has been bestowed with biographical meaning (Lupton 2015: 39), where a person’s territory of themselves is extended to. The performer is not confined to their individual physical body, but rather extend themselves through interactions and connections with things outside of their physical selves, and this gives birth to a new virtual body – the vtuber character. This is evident in the case of Nora Cat whose creator has extended and connected himself beyond his physical body into her as a virtual female body to birth a new identity. He has embodied her by using facial tracking and voice modification technology so that when he speaks, she speaks. When he smiles, she smiles. She becomes an extension of himself, he extends his physical and psychological forms through the technology used to perform her. The virtual avatar, the she, is not a separate being from him, she is him and thus his identity is her. He uses motion tracking technology so that how he moves is how she will move. He embodies and controls her voice, personality, mannerisms, and expressions. This is why some viewers could not separate the connection of Nora Cat from her creator because she exists as an extension of him. However, the other viewers who were able to define the two identities show what Haraway argues in that we are multiple bodies. Haraway’s cyborg (in Lupton 2015: 40) shows that we do not exist as singular individuals but rather as multiple bodies and selves in different contexts and engagements. Nora Cat’s creator has multiple bodies depending on the context in which they find themselves. In the real physical world, he is a male with a male body, but in the online virtual space, specifically YouTube, he is a female with a female body. He interacts with not only Nora Cat as a female, but with Nora Cat’s community (viewers and subscribers) as a female who in turn interact with her and not him. 
            </p>
            <p className='paragraph'>
            The role of babiniku community interaction can be understood through Bredikhina and Giard’s work as they state, “babiniku create a community based on a discourse of opposition to dominant gender norms” (2022: 1651). This highlights the tensions or gender politics surrounding Nora Cat’s gender reveal as the event becomes a representation of the contrast between Nora Cat’s gender identity, its relationship between virtual and real, and socially coded gender norms – Nora Cat is the opposing entity in this scenario. There is also the perspective of the viewer to take into consideration when discussing how vtuber gender identity complicates the study of online gender performance within the Digital Humanities. Turner introduces a new term attached to babiniku vtubers which is ‘nakanohito’ (2022: 16). It means the voice actor behind the character. Male nakanohito who are babiniku vtubers may hold a space for a portion of their community’s viewers who also do not conform to standardised gender codes. Turner’s research concludes that “trans and gender non-conforming communities” find that babiniku vtubers enabled them to “work towards their personal ideals, and to feel safer and more affirmed in their own identities” (2022: 30). The separation of the identities that babiniku represents is particularly important for these types of viewers, that there is a clear distinction between the real-life gender identity and the virtual and yet they coexist together as one, in this instance, as Nora Cat. Lupton’s, Bredikhina and Giard’s, and Turner’s work is crucial in understanding virtual embodiment and its relation to virtual gender identities and the communities that form around them, all necessary contributions to understanding vtuber’s identity and gender expression in the context of Digital Humanities. Their work helps to position Nora Cat’s face reveal in the context of gender performance and the event’s greater function in DH.
            </p>
            <p className='paragraph'>
            Reasons behind Nora Cat’s gender juxtaposition 
            </p>
            <p className='paragraph'>
            Why may have Nora Cat chosen a different gender identity to their real-life identity? And what does this say about online gender identity and performance? There are two factors to this question. First is in understanding why vtubers choose virtual identities over their real identity and second is in addressing the reasons behind babiniku.
            </p>
            <p className='paragraph'>
            The rapid development of the internet has produced increased risks to users and their privacy and security online. While much can be said about the digital data and information economy we live in today, this shorter paper positions vtuber privacy and security more to physical safety rather than data safety. One of the major risks of streamers, vtubers or IRL (in-real-life) streamers, offering their real identity online is the possibility of being doxed. Doxing refers to the “intentional public release onto the Internet of personal information about an individual by a third party, often with the intent to humiliate, threaten, intimidate, or punish the identified individual” (Douglas 2016: 199). A popular doxing activity, called ‘swatting’ (Mantilla in Douglas 2016: 205), is where a viewer uses a leaked physical address of a streamer and calls a S.W.A.T team to raid their house after giving false instigating information. Popular streamer, QTCinderella, now suffers from post-traumatic stress disorder after her boyfriend’s, another popular streamer named Ludwig, address was leaked and swatted (Arias 2022). In an even more severe case, the person being doxed and swatted was killed by the S.W.A.T team that raided them (Stewart, 2018). Doxing is only one example of how a streamer’s privacy and security can be jeopardised, but it shows the incentives around vtubers wanting to remain as anonymous as possible.
            </p>
            <p className='paragraph'>
            Some vtubers also hide their real identities from not only their viewers but hide their identities from their family and friends too. This is because some vtubers are expressing themselves in ways that they feel their family and friends would not accept or understand, particularly for those who are in the LGBTQ+ and babiniku sectors (Yeo 2022). Remaining anonymous behind the virtual character allows vtubers to feel they can express themselves freely and safely online. In some cases, like with Nora Cat, technical glitches can unfortunately occur. But for many vtubers, the element of anonymity is one of the biggest incentives to becoming a vtuber.
            </p>
            <p className='paragraph'>
            Furthering the discussion around incentive are the affordances of participating in babiniku. The babiniku vtubers that Bredikhina and Giard (2022) survey list many reasons as to why they perform as virtual bishōjo characters. Nora Cat is an example of a bishōjo avatar. She follows typical anime design conventions which include but are not limited to fair skin, blushed cheeks, a round face with a pointed chin, a small, usually undefined but cute mouth, and large, colourful, and spirited eyes. She has silver hair styled in anime fashion with cat ears, crimson eyes, and usually wears a black gothic Lolita dress (another typical style associated with cute anime design). Her character design is heavily influenced by bishōjo as her features like her facial features and expressions and her voice are catered to the femininity and beauty of typical bishōjo. These characters are usually highly sociable and loveable forming adoring and supportive communities around them. Babiniku vtubers felt that they would not have garnered their following had they either been their real selves or a male avatar because female avatars and bishōjo are better received by viewers (Bredikhina & Giard 2022, Bredikhina 2020). This shows the mobilisation of certain genders and gender codes in online spaces by vtubers. Babiniku vtubers leverage femininity to gain a following and connect with viewers who are more open to that connection because of bishōjo gender codes. One participant in Bredikhina and Giard’s study quite literally states, “I thought that having a feminine appearance would be the best solution to get attention” (2022: 1652). The authors further go on to posit that bishōjo increases a babiniku vtuber’s “popularity because of the character’s conceptual attributes” (Bredikhina & Giard 2022: 1652). Bishōjo also seem more desirable and allow for these vtubers to be “released from one’s physical gender identity and social norms” (Bredikhina 2020). Bredikhina states that these men are redefining social issues around social interaction and gender and body norms by mobilising the agency and freedom of expression that babiniku affords. This is echoed and developed on in Bredikhina and Giard (2022: 1653) as they describe Japan’s societal codes around the social pressures men face that restrict their questioning and own definition of manhood. Thus, performing bishōjo and participating in livestreaming as babiniku, these men, like Nora Cat’s creator, feel this mode of representation better suits their needs and wants as content creators. 
            </p>
            <p className='paragraph'>
            Self-representation in avatar imagery: the prosumption of imagery, technology, and gender 
            </p>
            <p className='paragraph'>
            The event thus far has directed the discussion through virtual embodiment and selfhood and online gender performance. What it also affords are insights into digital nuances of self-representation. The representation of the digital self in vtubing is done through the avatar. Teo (in Van der Walt 2018: 90) defines the avatar as “a public profile of the self-identity to present a chosen image”. Van der Walt furthers this by describing the avatar’s image as a persona that “presents a self-representation where certain identity traits are carefully selected and presented as public performance” (2018: 90). This is evident in Nora Cat’s choice of bishōjo imagery and traits in appearance and identity, as previously discussed. Nora Cat’s creator and nakanohito represent their ‘self’ online through the imagery of a virtual female avatar. 
            </p>
            <p className='paragraph'>
            Avatars and their imagery situated themselves in the global consumption of online and digital imagery. Also in this category are selfies. There is much scholarship around selfies and the abundant research on the topic offers various perspectives, but for the purpose of this paper I will draw from Willams and Marquez’ work. They define selfies as a “social tool that can be used in producing and consuming racial and gender identities” (Willams & Marquez 2015: 1775). Selfie imagery is prosumed through something the authors define as ‘conspicuous prosumption’ – the prosumption of “constructed experiences with the explicit intent of allowing others to share in those experiences” (2015: 1776). This is where the consumption of selfie-imagery is no different to the consumption of avatar imagery, as both are conspicuously prosumed. Vtubers create experiences through imagery to explicitly allow for others to share in the experience of the character. For example, during a livestream viewers can request outfit changes, bodily modifications, and interactions like the generic ‘head pat’. These interactions create a shared experience, between vtuber and viewer, that is facilitated by the imagery, technology, and gender a vtuber uses to represent themselves online. The imagery and gender of Nora Cat is that of bishōjo and the technology her creator uses enables them to self-represent as a bishōjo character. Streaming technology affords an actualisation of self-representation as vtuber streamers can “manipulate the structural building blocks of streaming (webcam, microphone, appearance, voice)” (Turner 2022: 17) their online and digital self. Thus, Nora Cat is an example of the intersections of imagery, technology, and gender than foreground online and virtual self-representation. 
            </p>
            <p className='paragraph'>
            Conclusion
            </p>
            <p className='paragraph'>
            The purpose of this paper was to use Nora Cat’s face reveal as a case study to analyse how gender is presented, mediated, and informed by online virtual content creators (vtubers). Nora Cat is an iconic example of how gender facets are defined, adopted, and performed in online digital spaces and what the implications offer when the true identity and gender of the content creator is revealed. Specifically pertaining to men who incarnate virtual female characters. The scholarship that this research engaged with offer many avenues in which gender identity can be learned about and analysed so that it may be applied to case studies like Nora Cat. Applying this knowledge furthers our understanding of how gender functions in online identity – an avenue of digital sociology in the Digital Humanities that affords insights into what constitutes the online digital human, real and virtual. 
            </p>
            <h1 className='main-heading'>1000 points to you if you made it this far!</h1>
            <p className='paragraph'>
            Reference List
            <br/>
            ARIAS, J. 2022. GAMERANT. QTCinderella Reveals She Has PTSD After Getting Swatted. Online. https://gamerant.com/qtcinderella-swatted-ptsd/. 15 April 2023.
            <br/>
            BASEEL, C. 2018. Sora News 24. Anime girl virtual YouTuber unmasked as middle-age male otaku, loses some fans, gains others. Online. https://soranews24.com/2018/02/06/anime-girl-virtual-youtuber-unmasked-as-middle-age-male-otaku-loses-some-fans-gains-others%E3%80%90vid%E3%80%91/. 15 April 2023.
            <br/>
            BREDIKHINA, L. 2020. Designing identity in VTuber Era. Conference: ConVRgence (VRIC) Virtual Reality International Conference Proceedings. https://www.researchgate.net/publication/363587218_Designing_identity_in_VTuber_Era. 
            <br/>
            BREDIKHINA, L., AND GIARD, A. 2022. Becoming a Virtual Cutie: Digital Cross-Dressing in Japan. Convergence, 28(6), 1643–1661.
            <br/>
            DOUGLAS, D., M. 2016. Doxing: a conceptual analysis. Ethics and Information Technology 18, 199-210. 
            <br/>
            LOVERIDGE, L. 2018. Anime News Network. Technical Glitch Reveals Virtual YouTuber's Real Identity. Online. https://www.animenewsnetwork.com/interest/2018-02-07/technical-glitch-reveals-virtual-youtuber-real-identity/.127488. 15 April 2023
            <br/>
            LUPTON, D. 2015. Digital Sociology. Introduction: Life is digital, and Chapter 2: Theorising digital society. In Digital Sociology, (pp. 1-41). Routledge. London and New York.
            <br/>
            LUPTON, D. 2015. Digital Sociology. Chapter 8: The digitised body/self. In Digital Sociology, (pp. 164-187). Routledge. London and New York.
            <br/>
            STEWART, E. 2018. Vox. Gamer who made “swatting” call over video game dispute now facing manslaughter charges. Online. https://www.vox.com/policy-and-politics/2018/1/13/16888710/barris-swatting-death-charges. 15 April 2023.
            <br/>
            TURNER, A., B. 2022. Streaming as a Virtual Being: The Complex Relationship Between VTubers and Identity. Malmö University.
            <br/>
            VAN DER WALT, J. P. 2018. Chapter 4: The Leadership Persona in #FeesMustFall A Platform for Self-Presentation. Voices from the South: Digital Arts and Humanities, (pp. 83–116). AOSIS, Cape Town.
            <br/>
            WILLAMS, A. A. & MARQUEZ, B. A. 2015. The Lonely Selfie King: Selfies and the Conspicuous Prosumption of Gender and Race. International Journal of Communication 9(2015), 1775-1787.
            <br/>
            YEO, N. 2022. VTUBERS: THE APPEAL OF CREATING A PUBLIC VIRTUAL IDENTITY. Debating Communities and Networks XIII. Accessed: https://networkconference.netstudies.org/2022/ioa/252/vtubers-the-appeal-of-creating-a-public-virtual-identity/.

            </p>
            </section>
        </article>
      </div>
    )
  }
}
